(set-logic QF_LRA)
(declare-const x Real)
(declare-const y Real)
(assert (>= (+ x (* 4 y)) 20))
(assert (<= (+ x (* 2 y)) 10))
(assert (<= (+ x y) 2))
(assert (>= (+ x (* 5 y)) 30))
(assert (<= (+ x (* 6 y)) 35))
(check-sat)
